<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\iCareCore.DAL\iCareCore.Infrastructure.csproj" />
    <ProjectReference Include="..\iCareCore.Models\iCareCore.Core.csproj" />
  </ItemGroup>

</Project>
